"""Add storage_path column to files

Revision ID: 31ac5838e09d
Revises: fa2da44bd1a0
Create Date: 2026-03-12 00:04:58.219125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ac5838e09d'
down_revision: Union[str, Sequence[str], None] = 'fa2da44bd1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('storage_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'storage_path')
    # ### end Alembic commands ###
