"""Added new column to job execution table

Revision ID: 390653a0e69c
Revises: 31ac5838e09d
Create Date: 2026-03-23 22:53:29.583129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390653a0e69c'
down_revision: Union[str, Sequence[str], None] = '31ac5838e09d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_executions', sa.Column('total_requests', sa.Integer(), nullable=True))
    op.add_column('job_executions', sa.Column('error_count', sa.Integer(), nullable=True))
    op.add_column('job_executions', sa.Column('max_latency', sa.Integer(), nullable=True))
    op.add_column('job_executions', sa.Column('alerts_generated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_executions', 'alerts_generated')
    op.drop_column('job_executions', 'max_latency')
    op.drop_column('job_executions', 'error_count')
    op.drop_column('job_executions', 'total_requests')
    # ### end Alembic commands ###
